Repository AY2223S2-CS2103T-T09-4/tp, pull requests merged in 2023-03, with the labels that each got.

#51 Merge Branch-readme
  README.md
  docs/DeveloperGuide.md
  docs/_config.yml
Labels: type.Bug

#57 Implement SelectCommand
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SelectCommandParser.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SelectCommandParserTest.java
Labels: priority.High, type.Task

#60 Add redo and undo feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAddressBook.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/VersionedAddressBookTest.java
Labels: type.Story, priority.High

#63 Integrate SelectCommand and PolicyList into GUI
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/client/Client.java
  src/main/java/seedu/address/model/client/UniqueClientList.java
  src/main/java/seedu/address/model/client/policy/UniquePolicyList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PolicyCard.java
  src/main/java/seedu/address/ui/PolicyListPanel.java
  src/main/resources/view/Base.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PolicyListCard.fxml
  src/main/resources/view/PolicyListPanel.fxml
  src/main/resources/view/Styles.css
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/client/ClientTest.java
  src/test/java/seedu/address/model/client/UniqueClientListTest.java
Labels: type.Story, priority.High

#90 Branch tituswe Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/StartSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/SelectSequenceDiagram.png
  docs/images/StartSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiPreview.png
  src/main/resources/view/Base.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/Styles.css
Labels: Project Website, type.Enhancement
